apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: php-server
          image: arun878/php-server:latest
          imagePullPolicy: Always